### ISSUE TITLE
Warning and print statement in lightcurve plotting

### ISSUE THREAD

**Issue by ajstewart** [askap-vast/vast-tools#331]
The source light curve plotting is issuing a warning along with a print statement which should be removed.

Culprit line for the print:
https://github.com/askap-vast/vast-tools/blob/10d8b92e75854e8c5636f28447f9cb2fb638c42d/vasttools/source.py#L523

Not sure where this warning is coming from:
```
/Users/adam/anaconda3/envs/vast-tools-dev-poetry/lib/python3.8/site-packages/matplotlib/axes/_base.py:2283: UserWarning: Warning: converting a masked element to nan.
  xys = np.asarray(xys)
```

<img width="1249" alt="Screen Shot 2022-03-03 at 15 32 20" src="https://user-images.githubusercontent.com/3306161/156597408-c058710c-761a-43a1-b544-41dc1b8f7e66.png">

**Comment by ddobie** [comment]
I've fixed the print statement.

I can reproduce the warning on ada but not on the hub. I haven't got a clue what's causing it though... as far as I can tell there's no masked elements?

**Comment by ajstewart** [comment]
> I've fixed the print statement.
> 
> I can reproduce the warning on ada but not on the hub. I haven't got a clue what's causing it though... as far as I can tell there's no masked elements?

Different matplotlib versions? I don't remember seeing it before the recent changes with the flux support and perhaps the fix of the legend marker? I reckon it's something to do with those.

**Comment by ddobie** [comment]
That's pretty likely. I'll take a look into it.

**Comment by ddobie** [comment]
It's definitely https://github.com/askap-vast/vast-tools/blob/5315aac838e954f9ef2007d529227e068f907807/vasttools/source.py#L597-L604

because the warning is resolved if you replace the nans with numbers. Interestingly, the warning remains if you replace them with `np.inf`. I did some searching on stack overflow and github and the warning itself seems to be for any non-plotted point rather than masked elements, so that's slightly frustrating as there's no real way to plot dummy points without triggering this warning.

There's ways to add legend elements without plotting them, but they're all more complex than our current implementation. I'm tempted to just add a warning filter to ignore it. What do you think?

**Comment by ajstewart** [comment]
> It's definitely
> 
> https://github.com/askap-vast/vast-tools/blob/5315aac838e954f9ef2007d529227e068f907807/vasttools/source.py#L597-L604
> 
> because the warning is resolved if you replace the nans with numbers. Interestingly, the warning remains if you replace them with `np.inf`. I did some searching on stack overflow and github and the warning itself seems to be for any non-plotted point rather than masked elements, so that's slightly frustrating as there's no real way to plot dummy points without triggering this warning.
> 
> There's ways to add legend elements without plotting them, but they're all more complex than our current implementation. I'm tempted to just add a warning filter to ignore it. What do you think?

How complex are we talking? Remind me, the original issue was that the error bar down arrow was not showing in the legend? Was it possible to fetch the legend object and add it manually? While the solution works it also doesn't seem ideal to plot NaN points if it is causing that warning.
